# Generated by Django 5.0.1 on 2024-01-12 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, verbose_name='item_name')),
                ('item_price', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='item_price')),
                ('order_quantity', models.IntegerField(default=1, verbose_name='order_quantity')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='amount')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.carthistory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_owner', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_shop', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_history',
            },
        ),
    ]
